FROM node:22

WORKDIR /app

# Install sqlite3 CLI for debugging
# RUN apt-get update && apt-get install -y sqlite3 \
#     && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3016
CMD ["npm", "run", "dev"]