cluster.name: "ft-transcendence-logs"
network.host: 0.0.0.0

# Discovery settings for single-node cluster
discovery.type: single-node

# Security settings
xpack.security.enabled: true
xpack.security.enrollment.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false

# Memory settings
bootstrap.memory_lock: false

# Data retention policies
indices.lifecycle.poll_interval: "10m"
