#!/bin/bash

# ELK Dashboard Guide for Grafana
# This script provides information about accessing and using ELK dashboards

echo "=========================================="
echo "   ELK DASHBOARDS IN GRAFANA"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}✓${NC} ELK Stack Dashboards Created Successfully!"
echo ""

echo "=========================================="
echo "   AVAILABLE DASHBOARDS"
echo "=========================================="
echo ""

echo -e "${BLUE}1. ELK Stack Monitoring${NC}"
echo "   URL: http://localhost:3000/d/elk-monitoring"
echo "   Description: Complete ELK stack overview"
echo "   Panels:"
echo "     • Log Events Over Time"
echo "     • Total Log Count"
echo "     • Error Count"
echo "     • Logs by Service"
echo "     • Logs by Level"
echo "     • Recent Logs Table"
echo "     • Elasticsearch JVM Heap Memory"
echo "     • Elasticsearch Document Count"
echo "     • Cluster Health Status"
echo "     • Number of Nodes"
echo "     • Total Indexed Documents"
echo ""

echo -e "${BLUE}2. Logstash Pipeline Monitoring${NC}"
echo "   URL: http://localhost:3000/d/logstash-pipeline"
echo "   Description: Logstash processing metrics"
echo "   Panels:"
echo "     • Logstash Input Rate"
echo "     • Events Processed"
echo "     • Filter Errors"
echo "     • Events by Container"
echo "     • Logs by Host"
echo "     • Recent Log Events"
echo "     • Log Levels Over Time"
echo "     • Average Document Size"
echo ""

echo -e "${BLUE}3. System Monitoring Dashboard${NC}"
echo "   URL: http://localhost:3000/d/system-monitoring"
echo "   Description: System resources monitoring"
echo ""

echo -e "${BLUE}4. Kafka Monitoring Dashboard${NC}"
echo "   URL: http://localhost:3000/d/kafka-monitoring"
echo "   Description: Kafka cluster metrics"
echo ""

echo "=========================================="
echo "   ACCESS INFORMATION"
echo "=========================================="
echo ""
echo "Grafana URL: http://localhost:3000"
echo "Username: hidriouc"
echo "Password: hidriouc"
echo ""

echo "=========================================="
echo "   DATA SOURCES"
echo "=========================================="
echo ""
echo "The dashboards use the following data sources:"
echo ""
echo -e "${GREEN}✓${NC} Prometheus (http://prometheus:9090)"
echo "   - System metrics"
echo "   - Application metrics"
echo "   - Elasticsearch metrics"
echo ""
echo -e "${GREEN}✓${NC} Elasticsearch (http://elasticsearch:9200)"
echo "   - Log data"
echo "   - Document statistics"
echo "   - Search queries"
echo ""
echo -e "${GREEN}✓${NC} Loki (http://loki:3100)"
echo "   - Container logs"
echo "   - Application logs"
echo ""

echo "=========================================="
echo "   DASHBOARD FEATURES"
echo "=========================================="
echo ""
echo "ELK Stack Monitoring Dashboard:"
echo "  • Real-time log event visualization"
echo "  • Error tracking and counting"
echo "  • Service-level log distribution"
echo "  • Log level breakdown"
echo "  • Elasticsearch health monitoring"
echo "  • JVM memory tracking"
echo "  • Document indexing statistics"
echo ""
echo "Logstash Pipeline Dashboard:"
echo "  • Input rate monitoring"
echo "  • Event processing statistics"
echo "  • Filter error detection"
echo "  • Container-based event tracking"
echo "  • Host distribution analysis"
echo "  • Log level trends"
echo "  • Document size analysis"
echo ""

echo "=========================================="
echo "   USEFUL QUERIES"
echo "=========================================="
echo ""
echo "In Grafana Explore, you can use these queries:"
echo ""
echo "Elasticsearch Queries:"
echo '  • All logs: *'
echo '  • Error logs: level:error OR level:ERROR'
echo '  • Specific service: service:"kafka"'
echo '  • Container logs: container.name:"kafka"'
echo '  • Time range: Use the time picker'
echo ""
echo "PromQL Queries:"
echo '  • ES heap usage: elasticsearch_jvm_memory_used_bytes{area="heap"}'
echo '  • ES cluster health: elasticsearch_cluster_health_status'
echo '  • Document count: elasticsearch_indices_docs'
echo ""

echo "=========================================="
echo "   QUICK TIPS"
echo "=========================================="
echo ""
echo "1. Time Range:"
echo "   • Use the time picker (top right) to adjust the time window"
echo "   • Default: Last 6 hours for ELK, Last 3 hours for Logstash"
echo ""
echo "2. Auto-Refresh:"
echo "   • Dashboards refresh every 10 seconds automatically"
echo "   • You can change this in the dashboard settings"
echo ""
echo "3. Filtering:"
echo "   • Click on any chart element to filter"
echo "   • Use the table filters to search logs"
echo "   • Hover over panels for detailed information"
echo ""
echo "4. Drill-Down:"
echo "   • Click on log entries to see full details"
echo "   • Use the Explore feature for custom queries"
echo ""
echo "5. Export:"
echo "   • Export dashboards as JSON"
echo "   • Share links with team members"
echo "   • Create snapshots for reporting"
echo ""

echo "=========================================="
echo "   VERIFICATION COMMANDS"
echo "=========================================="
echo ""
echo "Check Elasticsearch health:"
echo "  curl http://localhost:9200/_cluster/health | jq"
echo ""
echo "View Elasticsearch indices:"
echo "  curl http://localhost:9200/_cat/indices?v"
echo ""
echo "Test Logstash pipeline:"
echo "  curl http://localhost:9600/_node/stats | jq"
echo ""
echo "Check Kibana status:"
echo "  curl http://localhost:5601/api/status | jq"
echo ""
echo "List Grafana dashboards:"
echo '  curl -s -u hidriouc:hidriouc "http://localhost:3000/api/search?query=&type=dash-db" | jq'
echo ""

echo "=========================================="
echo "   TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "If dashboards show no data:"
echo ""
echo "1. Check if Elasticsearch is running:"
echo "   docker-compose ps elasticsearch"
echo ""
echo "2. Verify Logstash is processing logs:"
echo "   docker logs logstash --tail 50"
echo ""
echo "3. Check if data exists in Elasticsearch:"
echo "   curl http://localhost:9200/_cat/indices?v"
echo ""
echo "4. Verify Grafana data sources:"
echo "   Go to Configuration > Data Sources in Grafana"
echo ""
echo "5. Check logs are being generated:"
echo "   docker-compose logs kafka | head -20"
echo ""
echo "6. Restart the ELK stack if needed:"
echo "   docker-compose restart elasticsearch logstash kibana"
echo ""

echo "=========================================="
echo "   ACCESSING OTHER ELK COMPONENTS"
echo "=========================================="
echo ""
echo "Kibana (Native ELK UI):"
echo "  URL: http://localhost:5601"
echo "  • Advanced log search"
echo "  • Index management"
echo "  • Discover, Visualize, Dashboard"
echo ""
echo "Elasticsearch API:"
echo "  URL: http://localhost:9200"
echo "  • Direct API access"
echo "  • Index operations"
echo "  • Search queries"
echo ""
echo "Logstash API:"
echo "  URL: http://localhost:9600"
echo "  • Pipeline stats"
echo "  • Node information"
echo "  • Plugin status"
echo ""

echo "=========================================="
echo "   DASHBOARD CUSTOMIZATION"
echo "=========================================="
echo ""
echo "To customize dashboards:"
echo ""
echo "1. Click the dashboard settings icon (gear)"
echo "2. Select 'Make editable'"
echo "3. Add/remove panels as needed"
echo "4. Click 'Save dashboard'"
echo ""
echo "To create new panels:"
echo "1. Click 'Add panel'"
echo "2. Choose 'Add a new panel'"
echo "3. Select data source (Elasticsearch/Prometheus)"
echo "4. Write your query"
echo "5. Configure visualization"
echo "6. Save the panel"
echo ""

echo "=========================================="
echo "   PERFORMANCE TIPS"
echo "=========================================="
echo ""
echo "• Use specific time ranges to reduce query load"
echo "• Apply filters to narrow down data"
echo "• Adjust refresh intervals for better performance"
echo "• Archive old logs to reduce index size"
echo "• Monitor Elasticsearch heap usage"
echo "• Use index lifecycle management (ILM)"
echo ""

echo "=========================================="
echo "✅ ELK DASHBOARDS READY TO USE!"
echo "=========================================="
echo ""
echo "Navigate to: http://localhost:3000"
echo "Login with: hidriouc / hidriouc"
echo ""
echo "Happy monitoring! 📊"
echo ""
