filebeat.inputs:
  - type: docker
    containers.ids: '*'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]

logging.level: info
logging.to_files: false
